spring:
  main:
    web-application-type: none
process:
  people:
    path: C:\Temp\peopleandcars-exercise-master\data\car
    threads-count: 1
    thread-prefix: car
  cars:
    path: C:\Temp\peopleandcars-exercise-master\data\people
    threads-count: 2
    thread-prefix: peo
  relations:
    path: C:\Temp\peopleandcars-exercise-master\data
    threads-count: 3
    thread-prefix: rel